# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '5-wordwordle.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random

file1 = open ("5-wordsource.txt", "r")
t = random.randrange(1, 45)
uu = file1.readlines()[t]
e = str(uu.upper().strip())
counter = 0
dictionary = {
1: ["lineEdit_a","lineEdit_b","lineEdit_c","lineEdit_d","lineEdit_e"],
2:  ["lineEdit_f","lineEdit_g","lineEdit_h","lineEdit_m","lineEdit_i"],
3:  ["lineEdit_j","lineEdit_k","lineEdit_l","lineEdit_n","lineEdit_o"],
4:  ["lineEdit_p","lineEdit_q","lineEdit_r","lineEdit_s","lineEdit_t"],
5:  ["lineEdit_u","lineEdit_v","lineEdit_w","lineEdit_x","lineEdit_y"]
    
}

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 80, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.okbutton = QtWidgets.QPushButton(Dialog)
        self.okbutton.setGeometry(QtCore.QRect(160, 200, 93, 28))
        self.okbutton.setObjectName("okbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "You Lose"))
        self.okbutton.setText(_translate("Dialog", "Ok"))



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
      
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 499)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 61, 31))
        self.pushButton.setObjectName("pushButton")
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 400, 61, 31))
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.clicked.connect(self.next)
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 50, 55, 16))
        self.label.setText(e)
        self.label.setObjectName("label")
        self.winstreak2 = QtWidgets.QLabel(self.centralwidget)
        self.winstreak2.setGeometry(QtCore.QRect(160, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.winstreak2.setFont(font)
        self.winstreak2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.winstreak2.setText("")
        self.winstreak2.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.winstreak2.setObjectName("winstreak2")
        self.Winstreak = QtWidgets.QLabel(self.centralwidget)
        self.Winstreak.setGeometry(QtCore.QRect(80, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Winstreak.setFont(font)
        self.Winstreak.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Winstreak.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.Winstreak.setObjectName("Winstreak")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 110, 761, 271))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        self.lineEdit_a = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.lineEdit_a.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_a, 0, 0, 1, 1)
        
        self.lineEdit_b = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.lineEdit_b.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_b, 0, 1, 1, 1)
        
        self.lineEdit_c = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_c.setObjectName("lineEdit_c")
        self.lineEdit_c.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_c, 0, 2, 1, 1)
        
        self.lineEdit_d = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_d.setObjectName("lineEdit_d")
        self.gridLayout.addWidget(self.lineEdit_d, 0, 3, 1, 1)
        self.lineEdit_d.setMaxLength(1)
        
        self.lineEdit_e = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_e.setObjectName("lineEdit_e")
        self.lineEdit_e.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_e, 0, 4, 1, 1)
        self.lineEdit_e.returnPressed.connect(self.enter)
        
        self.lineEdit_f = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f.setObjectName("lineEdit_f")
        self.lineEdit_f.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_f, 1, 0, 1, 1)
        
        self.lineEdit_g = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_g.setObjectName("lineEdit_g")
        self.lineEdit_g.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_g, 1, 1, 1, 1)
        
        self.lineEdit_h = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.lineEdit_h.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_h, 1, 2, 1, 1)
        
        self.lineEdit_m = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_m.setObjectName("lineEdit_m")
        self.lineEdit_m.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_m, 1, 3, 1, 1)
        
        self.lineEdit_i = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_i.setObjectName("lineEdit_i")
        self.lineEdit_i.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_i, 1, 4, 1, 1)
        self.lineEdit_i.returnPressed.connect(self.enter)
        
        self.lineEdit_j = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_j.setObjectName("lineEdit_j")
        self.lineEdit_j.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_j, 2, 0, 1, 1)
        
        
        self.lineEdit_k = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_k.setObjectName("lineEdit_k")
        self.lineEdit_k.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_k, 2, 1, 1, 1)
        
        self.lineEdit_l = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_l.setObjectName("lineEdit_l")
        self.lineEdit_l.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_l, 2, 2, 1, 1)
        
        self.lineEdit_n = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.lineEdit_n.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_n, 2, 3, 1, 1)
        
        self.lineEdit_o = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_o.setObjectName("lineEdit_o")
        self.lineEdit_o.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_o, 2, 4, 1, 1)
        self.lineEdit_o.returnPressed.connect(self.enter)
        
        self.lineEdit_p = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_p.setObjectName("lineEdit_p")
        self.lineEdit_p.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_p, 3, 0, 1, 1)
        
        self.lineEdit_q = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_q.setObjectName("lineEdit_q")
        self.lineEdit_q.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_q, 3, 1, 1, 1)
        
        self.lineEdit_r = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_r.setObjectName("lineEdit_r")
        self.lineEdit_r.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_r, 3, 2, 1, 1)
        
        self.lineEdit_s = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_s.setObjectName("lineEdit_s")
        self.lineEdit_s.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_s, 3, 3, 1, 1)
        
        self.lineEdit_t = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.lineEdit_t.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_t, 3, 4, 1, 1)
        self.lineEdit_t.returnPressed.connect(self.enter)
        
        self.lineEdit_u = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_u.setObjectName("lineEdit_u")
        self.lineEdit_u.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_u, 4, 0, 1, 1)
        
        self.lineEdit_v = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_v.setObjectName("lineEdit_v")
        self.lineEdit_v.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_v, 4, 1, 1, 1)
        
        self.lineEdit_w = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_w.setObjectName("lineEdit_w")
        self.lineEdit_w.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_w, 4, 2, 1, 1)
        
        self.lineEdit_x = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.lineEdit_x.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_x, 4, 3, 1, 1)
        
        self.lineEdit_y = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.lineEdit_x.setMaxLength(1)
        self.lineEdit_y.returnPressed.connect(self.enter)
        
        self.gridLayout.addWidget(self.lineEdit_y, 4, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton_2.setText(_translate("MainWindow", "Next"))
        self.Winstreak.setText(_translate("MainWindow", "WinStreak:"))
    
    def enter(self):
        global counter
        counter += 1
        j = dictionary[counter]
        g = j
        h = e
        a = []
        j = 0
        for xx in g:
            widget= getattr(self,xx)
            widget.setReadOnly(True)
            oo = widget.text()
            a.append(oo)
            
        for x in range(5):
                if h[x] == a[x]:
                    y = getattr(self,g[x])
                    y.setStyleSheet("background-color: rgb(0, 170, 0);")
                    j +=1
                    
                elif a[x] in h:
                    p = getattr(self,g[x])
                    p.setStyleSheet("background-color: rgb(255, 255, 0);")
                    
                else:
                    i = getattr(self,g[x]) 
                    i.setStyleSheet("background-color: rgb(255, 0, 0);")   
                    
                    
                if j ==5:
                    self.pushButton_2.setEnabled(True)
                    
                    
                if counter == 5 and j != 5:
                    self.lose()
                    self.lose()
    
    
    def next( self):
            print("h")

    def lose(self):
        Dialog.show
        

    
    def lose(self):
        
        self.dialog = QtWidgets.QDialog()
        
        self.dialog_ui = Ui_Dialog()
        
        self.dialog_ui.setupUi(self.dialog)
        
        self.dialog_ui.okbutton.clicked.connect(self.dialog.close)
        
        self.dialog.exec_()
   
        
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    sys.exit(app.exec_())