# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import random
from PyQt5.QtGui import QFont

file1 = open ("5-wordsource.txt", "r")
t = random.randrange(1, 45)
uu = file1.readlines()[t]
e = str(uu.upper().strip())
counter = 0
winstreak = 0
dictionary = {
1: ["lineEdit_a","lineEdit_b","lineEdit_c","lineEdit_d","lineEdit_e"],
2:  ["lineEdit_f","lineEdit_g","lineEdit_h","lineEdit_m","lineEdit_i"],
3:  ["lineEdit_j","lineEdit_k","lineEdit_l","lineEdit_n","lineEdit_o"],
4:  ["lineEdit_p","lineEdit_q","lineEdit_r","lineEdit_s","lineEdit_t"],
5:  ["lineEdit_u","lineEdit_v","lineEdit_w","lineEdit_x","lineEdit_y"]
    
}

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 80, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.okbutton = QtWidgets.QPushButton(Dialog)
        self.okbutton.setGeometry(QtCore.QRect(160, 200, 93, 28))
        self.okbutton.setObjectName("okbutton")
        self.okbutton.clicked.connect(self.back)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "You Lose"))
        self.okbutton.setText(_translate("Dialog", "Ok"))

    def back(self):
        MainWindow2.close()
        MainWindow4.close()
        MainWindow.show()

class Ui_MainWindow4(object):
    def setupUi(self, MainWindow):
      
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 499)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 61, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.back)
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 400, 61, 31))
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.clicked.connect(self.next)
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 50, 55, 16))
        self.label.setText(e)
        self.label.setObjectName("label")
        self.winstreak2 = QtWidgets.QLabel(self.centralwidget)
        self.winstreak2.setGeometry(QtCore.QRect(160, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.winstreak2.setFont(font)
        self.winstreak2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.winstreak2.setText(str(winstreak))
        self.winstreak2.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.winstreak2.setObjectName("winstreak2")
        self.Winstreak = QtWidgets.QLabel(self.centralwidget)
        self.Winstreak.setGeometry(QtCore.QRect(80, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Winstreak.setFont(font)
        self.Winstreak.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Winstreak.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.Winstreak.setObjectName("Winstreak")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 110, 761, 271))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        self.lineEdit_a = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.lineEdit_a.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_a, 0, 0, 1, 1)
     
        
        
        self.lineEdit_b = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.lineEdit_b.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_b, 0, 1, 1, 1)
        
        self.lineEdit_c = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_c.setObjectName("lineEdit_c")
        self.lineEdit_c.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_c, 0, 2, 1, 1)
        
        self.lineEdit_d = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_d.setObjectName("lineEdit_d")
        self.gridLayout.addWidget(self.lineEdit_d, 0, 3, 1, 1)
        self.lineEdit_d.setMaxLength(1)
        
        self.lineEdit_e = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_e.setObjectName("lineEdit_e")
        self.lineEdit_e.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_e, 0, 4, 1, 1)
        self.lineEdit_e.returnPressed.connect(self.enter)
        
        self.lineEdit_f = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f.setObjectName("lineEdit_f")
        self.lineEdit_f.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_f, 1, 0, 1, 1)
        
        self.lineEdit_g = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_g.setObjectName("lineEdit_g")
        self.lineEdit_g.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_g, 1, 1, 1, 1)
        
        self.lineEdit_h = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.lineEdit_h.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_h, 1, 2, 1, 1)
        
        self.lineEdit_m = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_m.setObjectName("lineEdit_m")
        self.lineEdit_m.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_m, 1, 3, 1, 1)
        
        self.lineEdit_i = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_i.setObjectName("lineEdit_i")
        self.lineEdit_i.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_i, 1, 4, 1, 1)
        self.lineEdit_i.returnPressed.connect(self.enter)
        
        self.lineEdit_j = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_j.setObjectName("lineEdit_j")
        self.lineEdit_j.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_j, 2, 0, 1, 1)
        
        
        self.lineEdit_k = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_k.setObjectName("lineEdit_k")
        self.lineEdit_k.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_k, 2, 1, 1, 1)
        
        self.lineEdit_l = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_l.setObjectName("lineEdit_l")
        self.lineEdit_l.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_l, 2, 2, 1, 1)
        
        self.lineEdit_n = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.lineEdit_n.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_n, 2, 3, 1, 1)
        
        self.lineEdit_o = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_o.setObjectName("lineEdit_o")
        self.lineEdit_o.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_o, 2, 4, 1, 1)
        self.lineEdit_o.returnPressed.connect(self.enter)
        
        self.lineEdit_p = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_p.setObjectName("lineEdit_p")
        self.lineEdit_p.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_p, 3, 0, 1, 1)
        
        self.lineEdit_q = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_q.setObjectName("lineEdit_q")
        self.lineEdit_q.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_q, 3, 1, 1, 1)
        
        self.lineEdit_r = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_r.setObjectName("lineEdit_r")
        self.lineEdit_r.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_r, 3, 2, 1, 1)
        
        self.lineEdit_s = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_s.setObjectName("lineEdit_s")
        self.lineEdit_s.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_s, 3, 3, 1, 1)
        
        self.lineEdit_t = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.lineEdit_t.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_t, 3, 4, 1, 1)
        self.lineEdit_t.returnPressed.connect(self.enter)
        
        self.lineEdit_u = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_u.setObjectName("lineEdit_u")
        self.lineEdit_u.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_u, 4, 0, 1, 1)
        
        self.lineEdit_v = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_v.setObjectName("lineEdit_v")
        self.lineEdit_v.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_v, 4, 1, 1, 1)
        
        self.lineEdit_w = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_w.setObjectName("lineEdit_w")
        self.lineEdit_w.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_w, 4, 2, 1, 1)
        
        self.lineEdit_x = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.lineEdit_x.setMaxLength(1)
        self.gridLayout.addWidget(self.lineEdit_x, 4, 3, 1, 1)
        
        self.lineEdit_y = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.lineEdit_y.setMaxLength(1)
        self.lineEdit_y.returnPressed.connect(self.enter)
        
        self.gridLayout.addWidget(self.lineEdit_y, 4, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton_2.setText(_translate("MainWindow", "Next"))
        self.Winstreak.setText(_translate("MainWindow", "WinStreak:"))
    
    def enter(self):
        global counter
        counter += 1
        j = dictionary[counter]
        g = j
        h = e
        a = []
        j = 0
        for xx in g:
            widget= getattr(self,xx)
            widget.setReadOnly(True)
            oo = widget.text()
            a.append(oo)
            
        for x in range(5):
                if h[x] == a[x]:
                    y = getattr(self,g[x])
                    y.setStyleSheet("background-color: rgb(0, 170, 0);")
                    j +=1
                    
                elif a[x] in h:
                    p = getattr(self,g[x])
                    p.setStyleSheet("background-color: rgb(255, 255, 0);")
                    
                else:
                    i = getattr(self,g[x]) 
                    i.setStyleSheet("background-color: rgb(255, 0, 0);")   
                    
                if j ==5:
                    self.pushButton_2.setEnabled(True)
                    
                if counter == 5 and j != 5:
                    self.lose()
    
    
    def next( self):
            global winstreak
            MainWindow4.close()
            MainWindow4.show()

    def lose(self):
        MainWindow2.show()
       
        
    def back(self):
        MainWindow4.close()
        MainWindow.show()
        
   


class statistic(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 581, 501))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(230, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 50, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 90, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 210, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(40, 260, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(40, 300, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(40, 350, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Statistics"))
        self.label_2.setText(_translate("MainWindow", "Time:"))
        self.label_3.setText(_translate("MainWindow", "Name: "))
        self.label_4.setText(_translate("MainWindow", "UID: "))
        self.label_5.setText(_translate("MainWindow", "Wins:"))
        self.label_6.setText(_translate("MainWindow", "Lose:"))
        self.label_7.setText(_translate("MainWindow", "Win/Lose Percentage:"))
        self.label_8.setText(_translate("MainWindow", "Most letter seen: "))



        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 390, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.statistic)
        
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 470, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.exit)
        
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 200, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 80, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        
        
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(70, 10, 121, 31))
        self.label_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_23.setFrameShape(QtWidgets.QFrame.Box)
        self.label_23.setLineWidth(1)
        self.label_23.setText("")
        self.label_23.setObjectName("label_2")
        
        
        start = time.time()
        local_time = time.ctime(start)
        self.label_23.setText(local_time)
        
        
        
        
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 320, 141, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.text)
        
        
        
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(180, 240, 241, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("4 Word wordle")
        self.comboBox.addItem("5 Word wordle")
        self.comboBox.addItem("6 Word wordle")
        self.comboBox.setItemText(3, "")
        text = str(self.comboBox.currentText())
       
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PRoFILE / STATISTIC"))
        self.pushButton_2.setText(_translate("MainWindow", "EXIT"))
        self.label.setText(_translate("MainWindow", "DIFFICULTY"))
        self.label_2.setText(_translate("MainWindow", "WORDLE"))
        self.pushButton_3.setText(_translate("MainWindow", "PLAY"))
     
        
    
    def exit(self):
        exit()
        
    def statistic(self):
        MainWindow.close()
        MainWindow3.show()
        
    def text(self):
        gg = (self.comboBox.currentText())
        if gg == "5 Word wordle":
            
            MainWindow.close()
            MainWindow4.show()
            
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow3 = QtWidgets.QMainWindow()
    MainWindow4 = QtWidgets.QMainWindow()
    MainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui2 = Ui_Dialog()
    ui3 =  statistic()
    ui4 = Ui_MainWindow4()
    ui3.setupUi(MainWindow3)
    ui2.setupUi(MainWindow2)
    ui.setupUi(MainWindow)
    ui4.setupUi(MainWindow4)
    MainWindow.show()
    sys.exit(app.exec_())