# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wordle.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random

file1 = open ("5-wordsource.txt", "r")
t = random.randrange(1, 45)
uu = file1.readlines()[t]
e = str(uu.capitalize().strip())
class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
         
        
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 140, 421, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(19, 0, 0, 0)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        
        self.first = QtWidgets.QLineEdit(self.layoutWidget)
        self.first.setMaxLength(1)
        self.first.setObjectName("first")
        self.horizontalLayout.addWidget(self.first)
        
        
        self.second = QtWidgets.QLineEdit(self.layoutWidget)
        self.second.setMaxLength(1)
        self.second.setObjectName("second")
        self.horizontalLayout.addWidget(self.second)
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 50, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        
        self.third = QtWidgets.QLineEdit(self.layoutWidget)
        self.third.setText("")
        self.third.setMaxLength(1)
        self.third.setObjectName("third")
        self.horizontalLayout.addWidget(self.third) 
              
        
        
        
        self.fourth = QtWidgets.QLineEdit(self.layoutWidget)
        self.fourth.setMaxLength(1)
        self.fourth.setObjectName("fourth")
        self.horizontalLayout.addWidget(self.fourth)
        
        
        self.fifth = QtWidgets.QLineEdit(self.layoutWidget)
        self.fifth.setMaxLength(1)
        self.fifth.setObjectName("fifth")
        self.fifth.returnPressed.connect(self.enter)
        
        
        self.horizontalLayout.addWidget(self.fifth)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 260, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setEnabled(False)
        
        self.first = QtWidgets.QLineEdit(self.layoutWidget)
        self.first.setMaxLength(1)
        self.first.setObjectName("first")
        self.horizontalLayout.addWidget(self.first)
        
        
        self.second = QtWidgets.QLineEdit(self.layoutWidget)
        self.second.setMaxLength(1)
        self.second.setObjectName("second")
        self.horizontalLayout.addWidget(self.second)
        
        
        
        self.third = QtWidgets.QLineEdit(self.layoutWidget)
        self.third.setText("")
        self.third.setMaxLength(1)
        self.third.setObjectName("third")
        self.horizontalLayout.addWidget(self.third) 
              
        
        
        
        self.fourth = QtWidgets.QLineEdit(self.layoutWidget)
        self.fourth.setMaxLength(1)
        self.fourth.setObjectName("fourth")
        self.horizontalLayout.addWidget(self.fourth)
        
        
        self.fifth = QtWidgets.QLineEdit(self.layoutWidget)
        self.fifth.setMaxLength(1)
        self.fifth.setObjectName("fifth")
        self.fifth.returnPressed.connect(self.enter)
        
        
        self.horizontalLayout.addWidget(self.fifth)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 260, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setEnabled(False)
        
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
    
    def enter(self):
        g = ["first","second","third","fourth","fifth"]
        h = e
        a = []
        j = 0
        for xx in g:
            widget= getattr(self,xx)
            widget.setReadOnly(True)
            oo = widget.text()
            a.append(oo)
            
        for x in range(5):
                if h[x] == a[x]:
                    y = getattr(self,g[x])
                    y.setStyleSheet("background-color: rgb(0, 170, 0);")
                    j +=1
                    
                elif a[x] in h:
                    p = getattr(self,g[x])
                    p.setStyleSheet("background-color: rgb(255, 255, 0);")
                    
                else:
                    i = getattr(self,g[x]) 
                    i.setStyleSheet("background-color: rgb(255, 0, 0);")   
                    
                    
                if j ==5:
                    self.pushButton.setEnabled(True)
                    MainWindow.show()

                    
        
        
            # if h[x] in h:
            #     h[x]
            # else 
            
            
        # self.fifth.text()    
        # self.fifth.setReadOnly(True)
        # self.fifth.setStyleSheet("background-color: rgb(255, 0, 0);")
        # for x in range(5):
        #     if h[x] == 
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
