# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import random
from PyQt5.QtGui import QFont

from mainscreen import mainwindow
from statistic import statistic
from fivewordwordle import fivewordwordle                                                                       
from losedialog import losedialog


    
    
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
   
    ui = mainwindow()
    ui2 = losedialog()
    ui3 =  statistic()
    ui4 = fivewordwordle()
    
    
    MainWindow1 = QtWidgets.QMainWindow()
    MainWindow3 = QtWidgets.QMainWindow()
    MainWindow4 = QtWidgets.QMainWindow()
    MainWindow2 = QtWidgets.QMainWindow()
    
    ui3.setupUi(MainWindow3)
    ui2.setupUi(MainWindow2)
    ui.setupUi(MainWindow1)
    ui4.setupUi(MainWindow4)
    
    MainWindow1.show()
    sys.exit(app.exec_())
    